services:
  pg:
    image: bitnami/postgresql
    ports:
      - '5432:5432'
    environment:
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_DB=${POSTGRES_DB}"
    restart: always
  redis:
    image: bitnami/redis
    ports:
      - '6379:6379'
    environment:
      - "REDIS_MASTER_PASSWORD=${REDIS_MASTER_PASSWORD}"
      - "REDIS_PASSWORD=${REDIS_PASSWORD}"
    restart: always
